"""Add user location

Revision ID: 60383255e628
Revises: 9998745a5cf4
Create Date: 2019-01-25 20:13:20.599472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60383255e628'
down_revision = '9998745a5cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('country_iso_code', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('country_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('location_latitude', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('location_longitude', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('postal_code', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('subdivisions_iso_code', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('subdivisions_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subdivisions_name')
    op.drop_column('user', 'subdivisions_iso_code')
    op.drop_column('user', 'postal_code')
    op.drop_column('user', 'location_longitude')
    op.drop_column('user', 'location_latitude')
    op.drop_column('user', 'country_name')
    op.drop_column('user', 'country_iso_code')
    op.drop_column('user', 'city_name')
    # ### end Alembic commands ###
