"""Added ip adresses to users tables

Revision ID: 9998745a5cf4
Revises: a2cc292061a1
Create Date: 2019-01-25 18:00:25.882250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9998745a5cf4'
down_revision = 'a2cc292061a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_login_ip', sa.String(length=40), nullable=True))
    op.add_column('user', sa.Column('last_login_ip', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'current_login_ip')
    # ### end Alembic commands ###
